In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cvxpy as cp

In [2]:
df = pd.read_excel('data.xlsx', header=None)
data = df.values.flatten()
requirements = data

In [3]:
requirements1 = requirements[0:8]
k = 10
requirements1

array([11,  5,  4,  7, 16,  6,  5,  7], dtype=int64)

In [4]:
hand_new = cp.Variable(8, integer=True)
hand_work = cp.Variable(8, integer=True)
hand_rest = cp.Variable(8, integer=True)
hand_teach = cp.Variable(8, integer=True)
hand_skill = cp.Variable(8, integer=True)
# body_new = cp.Variable(8, integer=True)
# body_work = cp.Variable(8, integer=True)
# body_rest = cp.Variable(8, integer=True)
# body_tested = cp.Variable(8, integer=True)

In [5]:
cons = [
    hand_work == 4 * requirements1,
    # body_work == requirements1,
    k * hand_teach >= hand_new,
    hand_skill == hand_work + hand_rest + hand_teach,
    # body_tested == body_work + body_rest,
    hand_new >= 0,
    hand_rest >= 0,
    hand_work >= 0,
    hand_teach >= 0,
    # body_new >= 0,
    # body_rest >= 0,
    # body_work >= 0,

    # hand_rest[1:] >= hand_work[:-1],
    # hand_skill[1:] == hand_skill[:-1] + hand_skill[:-1],
    # body_tested[1:] == body_tested[:-1] + body_new[:-1],

    hand_skill[0] == 50,
    # body_tested[0] == 13
]

In [6]:
obj = cp.Minimize(
    # 200 * cp.sum(body_new) + 
    100 * cp.sum(hand_new) + 
    5 * cp.sum(hand_rest) + 
    # 10 * cp.sum(body_rest) +
    10 * cp.sum(hand_new + hand_teach)
)

In [7]:
for t in range(7):
    cons.append(hand_rest[t+1] >= hand_work[t]),
    cons.append(hand_skill[t+1] == hand_skill[t] + hand_new[t])
    # cons.append(body_tested[t+1] == body_tested[t] + body_new[t])

In [8]:
prob = cp.Problem(obj, cons)
prob.solve()

6475.0

In [9]:
hand_work.value, prob.value

(array([44., 20., 16., 28., 64., 24., 20., 28.]), 6475.0)

In [10]:
hand_new.value, hand_teach.value

(array([14., -0., -0., 28.,  0.,  0.,  0.,  0.]),
 array([ 2., -0., -0.,  3.,  0.,  0.,  0.,  0.]))