In [1]:
import numpy as np
import pandas as pd

requirements = pd.read_excel('data.xlsx', header=None).values.flatten()
total_week = 104
WASTE_RATE = 0.1

In [2]:
requirements

array([ 11,   5,   4,   7,  16,   6,   5,   7,  13,   6,   5,   7,  12,
         5,   4,   6,   9,   5,   5,  11,  29,  21,  17,  20,  27,  13,
         9,  10,  16,   6,   5,   7,  11,   5,   5,   6,  12,   7,   7,
        10,  15,  10,   9,  11,  15,  10,  10,  16,  26,  21,  23,  36,
        50,  45,  45,  49,  57,  43,  40,  44,  52,  43,  42,  45,  52,
        41,  39,  41,  48,  35,  34,  35,  42,  34,  36,  43,  55,  48,
        54,  65,  80,  70,  74,  85, 101,  89,  88,  90, 100,  87,  88,
        89, 104,  89,  89,  90, 106,  96,  94,  99, 109,  99,  96, 102],
      dtype=int64)

## 递推法求容器艇数量

非常简单，实际上每周的潜艇数量必定需要等于需求量，而缺潜艇时在上一周补买就行。

模拟方法直接做。

In [4]:
total_bodies = 13

bodies_work = np.zeros(total_week)
bodies_waste = 4 * np.
bodies_new = np.zeros(total_week)

bodies_work[0] = requirements[0]

In [5]:
t = 1 # 1 代表第二周
while(t < total_week):
    # 需要的工作艇数量等于需求数
    body_work = requirements[t]
    # 若超过当前购买量
    if body_work > total_bodies:
        # 上一周应该买一些艇
        bodies_new[t - 1] = body_work - total_bodies
        total_bodies = body_work
    bodies_work[t] = requirements[t]
    t += 1


In [6]:
bodies_work

array([11.,  5.,  4.,  7., 16.,  6.,  5.,  7., 13.,  6.,  5.,  7., 12.,
        5.,  4.,  6.])

以上是模拟方法，可以发现这个方法非常冗余，我们直接求解也可以：

In [3]:
bodies_work = np.array(requirements[0:total_week])
bodies_new = np.zeros(total_week)
bodies_rest = np.zeros(total_week)
bodies_rest[0] = 13 - requirements[0]
total_bodies = 13
for t in range(1, total_week):
    if total_bodies < bodies_work[t]:
        bodies_new[t-1] = bodies_work[t] - total_bodies
        total_bodies = bodies_work[t]
    bodies_rest[t] = total_bodies - bodies_work[t]

In [4]:
np.concatenate([bodies_work.reshape(1, -1), bodies_new.reshape(1, -1), bodies_rest.reshape(1, -1)], axis=0)

array([[ 11.,   5.,   4.,   7.,  16.,   6.,   5.,   7.,  13.,   6.,   5.,
          7.,  12.,   5.,   4.,   6.,   9.,   5.,   5.,  11.,  29.,  21.,
         17.,  20.,  27.,  13.,   9.,  10.,  16.,   6.,   5.,   7.,  11.,
          5.,   5.,   6.,  12.,   7.,   7.,  10.,  15.,  10.,   9.,  11.,
         15.,  10.,  10.,  16.,  26.,  21.,  23.,  36.,  50.,  45.,  45.,
         49.,  57.,  43.,  40.,  44.,  52.,  43.,  42.,  45.,  52.,  41.,
         39.,  41.,  48.,  35.,  34.,  35.,  42.,  34.,  36.,  43.,  55.,
         48.,  54.,  65.,  80.,  70.,  74.,  85., 101.,  89.,  88.,  90.,
        100.,  87.,  88.,  89., 104.,  89.,  89.,  90., 106.,  96.,  94.,
         99., 109.,  99.,  96., 102.],
       [  0.,   0.,   0.,   3.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  13.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,

## 尝试将递推数列方法推广到机械手

难点：机械手的训练需要教练，教练也需要从全体机械手抽取。也就是说，如果机械手不足，我们回溯到上一周，新买一些机械手后，可能导致新买的机械手没人教，这样又要继续回溯到上上周，以此类推。

In [9]:
bodies_work = 4 * np.array(requirements[0:total_week])
bodies_new = np.zeros(total_week)
bodies_rest = np.zeros(total_week)
bodies_teach = np.zeros(total_week)
total_bodies = np.zeros(total_week)
total_bodies[0] = 50
available_bodies = np.zeros(total_week)
available_bodies[0] = 50
bodies_rest[0] = total_bodies[0] - bodies_work[0]

In [ ]:
# 模拟方法，硬解
for t in range(1, total_week):
    available_bodies[t] = total_bodies[t - 1] - 
    if total_bodies[t - 1] < bodies_work