In [1]:
import cvxpy as cp
import numpy as np
import pandas as pd
import os

In [2]:
data1 = pd.read_excel(os.path.join('data', 'transportation_data.xlsx'), header=None)
data2 = data1.values
# Remove the total row and column
c = data2[:-1, :-1]
sr = data2[-1, :-1].reshape(1, -1)
sc = data2[:-1, -1].reshape(-1, 1)
c, sr, sc

(array([[6., 2., 6., 7., 4., 2., 5., 9.],
        [4., 9., 5., 3., 8., 5., 8., 2.],
        [5., 2., 1., 9., 7., 4., 3., 3.],
        [7., 6., 7., 3., 9., 2., 7., 1.],
        [2., 3., 9., 5., 7., 2., 6., 5.],
        [5., 5., 2., 2., 8., 1., 4., 3.]]),
 array([[35., 37., 22., 32., 41., 32., 43., 38.]]),
 array([[60.],
        [55.],
        [51.],
        [43.],
        [41.],
        [52.]]))

In [3]:
print(cp.installed_solvers())

['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCIPY', 'SCS']


In [6]:
x = cp.Variable((6, 8))
# 总运费为两个矩阵各元素之积再求和
obj = cp.Minimize(cp.sum(cp.multiply(c, x)))
con = [cp.sum(x, axis=1, keepdims=True) <= sc, cp.sum(x, axis=0, keepdims=True) == sr, x >= 0]
prob = cp.Problem(obj, con)
prob.solve(solver='GLPK_MI', verbose=True)

                                     CVXPY                                     
                                     v1.2.0                                    
(CVXPY) Apr 03 12:14:42 AM: Your problem has 48 variables, 3 constraints, and 0 parameters.
(CVXPY) Apr 03 12:14:42 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 03 12:14:42 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 03 12:14:42 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Apr 03 12:14:42 AM: Compiling problem (target solver=GLPK_MI).
(CVXPY) Apr 03 12:14:42 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing

664.0

In [7]:
prob.value, x.value

(664.0,
 array([[-0., 19., -0., -0., 41., -0., -0., -0.],
        [-0., -0., -0., 32., -0., -0., -0.,  1.],
        [-0., 12., 22., -0., -0., -0., 17., -0.],
        [-0., -0., -0., -0., -0.,  6., -0., 37.],
        [35.,  6., -0., -0., -0., -0., -0., -0.],
        [-0., -0., -0., -0., -0., 26., 26., -0.]]))